#!/usr/bin/env python3
"""Generate the one file every session reads before it asserts anything.

WHY THIS EXISTS. Every serious failure of 2026-08-24 shares one shape: a session
made a claim about the ecosystem from something other than the ecosystem. A
connected folder that was empty became "the repository is unreachable" (L-143).
The tail of an unsorted file became "the next free id" (L-151). A parent count
became "this arrived through a pull request" (L-161). Parent count, folder
emptiness and file tails are all proxies, and D-115 rules that a control queries
the thing it asserts.

A session cannot query the ecosystem if it does not know where the ecosystem is.
So this writes two artefacts, both generated and never hand-edited:

    ops/PATH_REGISTRY.json    where everything actually is, and which lookalike
                              paths are decoys
    ops/ECOSYSTEM_STATE.json  what is true right now, measured

Both are regenerated by the self-heal loop and by CI, so a stale copy is a build
failure rather than a trap. `--check` exits non-zero when the committed copy
disagrees with a fresh measurement, exactly like build_graph and build_eval.

Usage:
    python scripts/build_ecosystem_state.py
    python scripts/build_ecosystem_state.py --check
    python scripts/build_ecosystem_state.py --selftest   # V-2 fixtures
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATE = ROOT / "ops" / "ECOSYSTEM_STATE.json"
REGISTRY = ROOT / "ops" / "PATH_REGISTRY.json"

#: The authoritative locations. Absolute, and paired with the lookalikes that
#: have already cost sessions. A path here is CHECKED before it is reported.
CANONICAL = {
    "qesis-mcp": {
        "path": r"C:\Users\Lenovo\qesis-mcp",
        "role": "served surface, MCP server, index artefact, CI gates, landing page",
        "decoys": [],
    },
    "sovereign-infra": {
        "path": r"C:\Users\Lenovo\OneDrive\sovereign-infra",
        "role": "evidence plane, ops ledgers, agent runtime, governance record",
        "decoys": [
            {
                "path": r"C:\Users\Lenovo\sovereign-infra",
                "why": "Empty stub. Held zero files since at least 2026-08-15 and "
                       "five consecutive sessions read its emptiness as a failed "
                       "mount or a broken sync bridge. L-143. It is not the "
                       "repository and never was.",
            }
        ],
    },
    "operational-store": {
        "path": r"C:\Users\Lenovo\OneDrive\sovereign-infra\var\qesis_ops.sqlite",
        "role": "compliance chain, Article 14 queue, task board, RDL defect table",
        "decoys": [],
    },
    "thesis-governance": {
        "path": r"C:\Users\Lenovo\OneDrive\Documents\INITIUM\Master IR & GE\Final Master Thesis\_GOVERNANCE",
        "role": "decision log, asset register, provenance manifest. NOT reachable "
                "from a GitHub runner, so anything measured here is desktop-only.",
        "decoys": [],
    },
}


def sh(*args: str) -> str:
    try:
        p = subprocess.run(args, cwd=ROOT, capture_output=True, text=True,
                           timeout=120, check=False)
        return (p.stdout + p.stderr).strip()
    except Exception as exc:
        return f"{type(exc).__name__}: {exc}"


def probe(path: str) -> dict:
    """State the existence of a path as a fact about that path. L-143, D-115."""
    p = Path(path)
    if not p.exists():
        return {"exists": False, "note": "not present on this filesystem"}
    if p.is_file():
        return {"exists": True, "kind": "file", "bytes": p.stat().st_size}
    try:
        n = sum(1 for _ in p.iterdir())
    except OSError as exc:
        return {"exists": True, "kind": "dir", "note": f"unreadable: {exc.strerror}"}
    return {"exists": True, "kind": "dir", "entries": n,
            "is_git_repo": (p / ".git").is_dir()}


def build_registry() -> dict:
    doc = {
        "_doc": "Authoritative absolute paths. Read this BEFORE asserting that "
                "anything is missing, unreachable or empty. A folder whose name "
                "matches is not therefore the thing. Generated by "
                "scripts/build_ecosystem_state.py, never hand-edited.",
        "_rule": "When a connected folder that should hold a known repository is "
                 "empty, that is a fact about that one path. Check the canonical "
                 "path here before reporting the source as unreachable. L-143.",
        "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "canonical": {},
    }
    for name, spec in CANONICAL.items():
        entry = {"path": spec["path"], "role": spec["role"],
                 "probe": probe(spec["path"]), "decoys": []}
        for d in spec["decoys"]:
            entry["decoys"].append({**d, "probe": probe(d["path"])})
        doc["canonical"][name] = entry
    return doc


def ledger_facts() -> dict:
    out = sh(sys.executable, str(ROOT / "scripts" / "verify_ledger_singleton.py"), "--json")
    try:
        d = json.loads(out)
        return {"entries": d.get("entries"), "unique": d.get("unique"),
                "max": f"L-{d.get('max', 0):03d}", "sha256": d.get("sha256"),
                "status": d.get("status")}
    except Exception:
        return {"status": "UNREADABLE", "detail": out[:200]}


def ladder_facts() -> dict:
    p = ROOT / "ops" / "RDL_LADDER.json"
    b = ROOT / "ops" / "RDL_BASELINE.json"
    fams = {}
    if p.exists():
        try:
            fams = json.loads(p.read_text(encoding="utf-8")).get("families", {})
        except Exception:
            pass
    gate = sh(sys.executable, str(ROOT / "scripts" / "rdl.py"), "ci-blocking")
    return {
        "families": len(fams),
        "at_rung_3_or_above": sorted(
            f for f, d in fams.items() if int(d.get("rung", 0)) >= 3),
        "baseline_recorded": b.exists(),
        "delta_gate": "PASSED" if "PASSED" in gate else
                      ("FAILED" if "FAILED" in gate else "UNKNOWN"),
    }


def vintage() -> str:
    for cand in ("data/qesis_v8.json", "data/index.json"):
        p = ROOT / cand
        if p.exists():
            try:
                d = json.loads(p.read_text(encoding="utf-8"))
            except Exception:
                continue
            for k in ("vintage", "canonical_vintage"):
                if isinstance(d, dict) and d.get(k):
                    return str(d[k])
                meta = d.get("meta") or d.get("provenance") or {}
                if isinstance(meta, dict) and meta.get(k):
                    return str(meta[k])
    return "not determinable from this checkout"


#: The one regex the two canonical ledger writers use, `verify_ledger_singleton`
#: and `rdl_append`. Copied deliberately rather than imported, because those are
#: scripts rather than a module; if it ever diverges the fixtures below fail.
_LEDGER_HEADER = re.compile(r"^\*\*L-(\d{3})", re.M)


def live_lesson_ids() -> set[int]:
    """Ids that already exist as ENTRIES in this repository's ledger.

    Read from the ledger itself, never from the state file that this function
    exists to make honest. D-115: a control queries the thing it asserts.
    """
    led = ROOT / "ops" / "LESSONS_LEDGER.md"
    if not led.exists():
        return set()
    return {int(m) for m in
            _LEDGER_HEADER.findall(led.read_text(encoding="utf-8", errors="replace"))}


def pending_facts(ops: Path, live: set[int]) -> tuple[list, list]:
    """Split the RDL pending files into work that is outstanding and residue.

    WHY THE SPLIT. Reading the pending file alone answers "which ids does this
    file name", and the question every session actually asks is "which lessons
    are still unappended". Those differ the moment an append succeeds and the
    file survives it, which is the state measured on 2026-08-28: ten ids named
    by the file, all ten already live in the ledger, and ECOSYSTEM_STATE telling
    every session that ten lessons were outstanding. That is D-115's own failure
    mode inside the file written to prevent it, so the fix belongs here and not
    in whatever leaves the residue behind.

    Consumed ids are REPORTED rather than dropped. An id that silently vanishes
    from this file cannot be distinguished from an id nobody ever reserved, and
    a known thing is declared rather than erased (L-199).
    """
    pending: list[dict] = []
    consumed: list[dict] = []
    for f in sorted(ops.glob("RDL_PENDING*.md")) if ops.is_dir() else []:
        t = f.read_text(encoding="utf-8", errors="replace")
        ids = sorted({int(m) for m in re.findall(r"\*\*L-(\d{3})", t)})
        if not ids:
            continue
        out = [f"L-{i:03d}" for i in ids if i not in live]
        done = [f"L-{i:03d}" for i in ids if i in live]
        if out:
            pending.append({"file": f.name, "ids": out})
        if done:
            consumed.append({
                "file": f.name,
                "ids": done,
                "note": "already entries in the ledger. The file is residue from an "
                        "append that succeeded, not outstanding work. Harmless: "
                        "rdl_append.py skips ids already present before it appends, "
                        "so no duplicate id can be created from this state.",
            })
    return pending, consumed


def build_state() -> dict:
    ops = ROOT / "ops"
    decisions = sorted(f.name for f in ops.glob("D-1*.md")) if ops.is_dir() else []
    pending, consumed = pending_facts(ops, live_lesson_ids())
    return {
        "_doc": "Measured state of the ecosystem. Every session reads this before "
                "asserting anything about the ecosystem. Generated, never hand "
                "written, regenerated by the self-heal loop and by CI. A stale "
                "copy fails the build rather than misleading a reader.",
        "_how_to_use": "This file answers 'what is true now'. ops/PATH_REGISTRY.json "
                       "answers 'where is everything'. CLAUDE.md answers 'what are "
                       "the rules'. Read all three at session start, in that order, "
                       "before running anything.",
        "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "repository": ROOT.name,
        "served_vintage": vintage(),
        "ledger": ledger_facts(),
        "rdl_ladder": ladder_facts(),
        "decision_documents_present": decisions,
        "promotion_policy_signed": (ops / "G-07_PROMOTION_POLICY_SIGNED.json").exists(),
        "rdl_pending_append": pending,
        "rdl_pending_consumed": consumed,
        "hard_constraints": [
            "No agent runs ANY git command from the zero-trust analysis mount, "
            "read-only included. status, add and diff each take .git/index.lock "
            "and abandon it, manufacturing the blocker the agent then reports. "
            "L-122, L-123, L-150.",
            "The authenticated push is the operator's, because the GitHub "
            "credential is his and no agent may hold it. G-03, G-04.",
            "Promotion and an Article 14 signature are the operator's. G-06 "
            "limit 2. Everything else an agent may do, it does. SH-10d.",
            "Lesson ids come from verify_ledger_singleton.py plus the pending "
            "reservations, never from the tail of the ledger. L-151.",
            "The lander is LAND_EVERYTHING_FINAL.bat in the sovereign-infra root. "
            "It is one double-click and it is idempotent.",
        ],
    }


def _strip_volatile(x):
    """Remove everything that legitimately differs between machines.

    `probe` results are host dependent by design: the Windows paths resolve on
    the operator's desktop, do not resolve on a GitHub runner, and do not resolve
    on the analysis mount. Comparing them would make --check fail on every
    machine that did not happen to generate the file, and the two would overwrite
    each other forever. That is a ping-pong, not a control. The DECLARED paths
    are compared; what a given filesystem can see of them is reported and not
    asserted as ecosystem state.

    The same argument covers ledger and ladder facts on a partial checkout, so
    those are compared only when both sides carry them.
    """
    # Everything MEASURED is stripped. This is the correction that matters.
    #
    # The first version compared the whole file, including ledger_facts and
    # ladder_facts. Those move whenever the ledger or the ladder moves, and the
    # lander regenerates the state BEFORE appending new lesson entries, so the
    # committed copy was stale the instant it was written. CI then failed on
    # every single run with "ECOSYSTEM_STATE.json disagrees with a fresh
    # measurement", which is a gate no correct action can satisfy: exactly the
    # deadlock SH-10f was written about, rebuilt one file later.
    #
    # What --check must actually guard is the STATIC CONTRACT a session reads at
    # start: where the repositories are, which lookalike paths are decoys, and
    # the hard constraints. Those do not move between runs. The measured block
    # stays IN the file, carries its own timestamp, and is informational.
    #
    # `repository` joined the set on 2026-08-24 evening (L-170). It is the NAME
    # OF THE CHECKOUT DIRECTORY, so it differs between the two repositories by
    # construction, and the same generated file is mirrored into both. Comparing
    # it made --check pass in qesis-mcp and fail in sovereign-infra on identical
    # bytes, which is the third occurrence of a gate no correct action could
    # satisfy: L-158, L-166, and this. The file still records it; it is a
    # measurement of where the file was generated, not a contract.
    # `rdl_pending_consumed` joined the set on 2026-08-28 with the same argument
    # that put `rdl_pending_append` here, and it is stated rather than assumed:
    # the two repositories hold DIFFERENT pending files by construction, because
    # the truncation that clears them survives in one checkout and not in the
    # other. Comparing it would make --check pass in qesis-mcp and fail in
    # sovereign-infra on a correct tree, which is L-158, L-166 and L-170 reached
    # a fourth time. It is measured, it stays IN the file, it is not a contract.
    VOLATILE = {
        "generated_utc", "probe", "repository",
        "ledger", "rdl_ladder", "served_vintage",
        "rdl_pending_append", "rdl_pending_consumed",
        "decision_documents_present",
        "promotion_policy_signed",
    }
    if isinstance(x, dict):
        return {k: _strip_volatile(v) for k, v in x.items() if k not in VOLATILE}
    if isinstance(x, list):
        return [_strip_volatile(v) for v in x]
    return x


def canon(d: dict) -> str:
    """Stable serialisation with volatile and host-dependent fields removed, so
    --check compares substance rather than the clock or the filesystem."""
    return json.dumps(_strip_volatile(json.loads(json.dumps(d))), sort_keys=True)


def check_files(fresh: dict) -> list[str]:
    """Compare committed copies against fresh measurements on the static contract only."""
    bad = []
    for path, doc in fresh.items():
        if not path.exists():
            bad.append(f"{path.name} is absent")
            continue
        try:
            have = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            bad.append(f"{path.name} is unreadable: {exc}")
            continue
        if canon(have) != canon(doc):
            bad.append(f"{path.name} disagrees with a fresh measurement")
    return bad


def selftest() -> int:
    """V-2. The check must ACCEPT a copy that differs only in what legitimately
    moves between machines and runs, and must REFUSE a copy whose static
    contract moved. Both halves, or the gate is a coin."""
    import copy as _copy
    import tempfile
    fails: list[str] = []
    n = 0  # L-201: a sub-suite reports the count it MEASURED, never a literal.
    state, registry = build_state(), build_registry()
    with tempfile.TemporaryDirectory() as d:
        sp, rp = Path(d) / "ECOSYSTEM_STATE.json", Path(d) / "PATH_REGISTRY.json"

        # ACCEPT: volatile drift only. Another repository, another clock,
        # another filesystem, another ledger hash, another vintage.
        s2, r2 = _copy.deepcopy(state), _copy.deepcopy(registry)
        s2["repository"] = "some-other-checkout-name"
        s2["generated_utc"] = "1999-01-01T00:00:00Z"
        s2["ledger"] = {"entries": 0, "sha256": "0" * 64, "status": "FAIL"}
        s2["served_vintage"] = "v0.0"
        s2["rdl_pending_append"] = []
        r2["generated_utc"] = "1999-01-01T00:00:00Z"
        for entry in r2["canonical"].values():
            entry["probe"] = {"exists": True, "kind": "dir", "entries": 999}
        sp.write_text(json.dumps(s2), encoding="utf-8")
        rp.write_text(json.dumps(r2), encoding="utf-8")
        if check_files({sp: state, rp: registry}):
            fails.append("volatile-only drift was refused")
        n += 1

        # REFUSE: a canonical path moved.
        r3 = _copy.deepcopy(registry)
        r3["canonical"]["sovereign-infra"]["path"] = r"C:\Users\Lenovo\sovereign-infra"
        rp.write_text(json.dumps(r3), encoding="utf-8")
        if not check_files({rp: registry}):
            fails.append("a moved canonical path was accepted")
        n += 1

        # REFUSE: a hard constraint dropped.
        s3 = _copy.deepcopy(state)
        s3["hard_constraints"] = s3["hard_constraints"][:-1]
        sp.write_text(json.dumps(s3), encoding="utf-8")
        if not check_files({sp: state}):
            fails.append("a dropped hard constraint was accepted")
        n += 1

        # REFUSE: absent and unreadable.
        rp.unlink()
        if not check_files({rp: registry}):
            fails.append("an absent registry was accepted")
        n += 1
        sp.write_text("{not json", encoding="utf-8")
        if not check_files({sp: state}):
            fails.append("an unreadable state file was accepted")
        n += 1

    # ------------------------------------------------------------------
    # pending_facts, the 2026-08-28 repair. An id already in the ledger is
    # residue; an id that is not is outstanding work. Both halves, or the
    # split is a coin (V-2).
    # ------------------------------------------------------------------
    with tempfile.TemporaryDirectory() as d:
        ops = Path(d)
        (ops / "RDL_PENDING_APPEND.md").write_text(
            "**L-193 \u00b7 a lesson that has already been appended** body\n\n"
            "**L-902 \u00b7 a lesson that has not** body\n", encoding="utf-8")
        pend, cons = pending_facts(ops, {193})

        # REFUSE: the exact defect measured on 2026-08-28.
        if any("L-193" in e["ids"] for e in pend):
            fails.append("an id already in the ledger was reported as pending")
        n += 1
        # ACCEPT: a genuinely unappended id is still reported.
        if not any("L-902" in e["ids"] for e in pend):
            fails.append("a genuinely pending id was dropped")
        n += 1
        # The consumed half is declared, never silently erased (L-199).
        if not any("L-193" in e["ids"] for e in cons):
            fails.append("a consumed id was erased instead of declared")
        n += 1

        # A file whose every id is live yields zero pending and is not listed.
        (ops / "RDL_PENDING_APPEND.md").write_text(
            "**L-193 \u00b7 every id in this file is live** body\n", encoding="utf-8")
        pend2, cons2 = pending_facts(ops, {193})
        if pend2:
            fails.append("a fully consumed file was still reported as pending")
        n += 1
        if not cons2:
            fails.append("a fully consumed file was not declared as consumed")
        n += 1

        # An empty pending file is neither pending nor consumed. Zero is zero.
        (ops / "RDL_PENDING_APPEND.md").write_text("", encoding="utf-8")
        if pending_facts(ops, {193}) != ([], []):
            fails.append("an empty pending file produced a row")
        n += 1

    # V-6: the reader is on trial against the system's own accessor, not against
    # itself. If `_LEDGER_HEADER` ever diverges from the regex the two canonical
    # ledger writers use, this is where it is caught rather than in production.
    lf = ledger_facts()
    if lf.get("status") == "PASS":
        live = live_lesson_ids()
        if len(live) != lf.get("entries"):
            fails.append(f"live_lesson_ids read {len(live)} ids while "
                         f"verify_ledger_singleton reports {lf.get('entries')}")
        n += 1
        if lf.get("max") not in {f"L-{i:03d}" for i in live}:
            fails.append(f"live_lesson_ids does not carry the accessor's max, {lf.get('max')}")
        n += 1

    for f in fails:
        print(f"SELFTEST FAIL: {f}")
    print(f"ECOSYSTEM STATE SELFTEST: "
          + (f"PASSED, {n} fixtures" if not fails else f"FAILED, {len(fails)} of {n}"))
    return 1 if fails else 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()

    if a.selftest:
        return selftest()

    fresh = {STATE: build_state(), REGISTRY: build_registry()}
    if a.check:
        bad = check_files(fresh)
        for b in bad:
            print(f"  STALE  {b}")
        print("ECOSYSTEM STATE CHECK " + ("FAILED" if bad else "PASSED"))
        if bad:
            print("  Regenerate with: python scripts/build_ecosystem_state.py")
        return 1 if bad else 0

    for path, doc in fresh.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(doc, indent=1) + "\n", encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}  "
              f"sha256 {hashlib.sha256(canon(doc).encode()).hexdigest()[:16]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
