# FIX_PR68.ps1
#
# PR #68 cannot merge because its branch was cut from 8b12760 instead of from
# main. The previous instruction chained git commands in PowerShell, where
# `git checkout main` failing on a dirty tree does NOT stop the next line, so
# `git checkout -b` branched from wherever HEAD already was. Three commits then
# replayed content main already carries under post-rebase hashes.
#
# The real delta is two inserted lines in the ledger and one new report file.
#
# EVERY git call is followed by an exit-code check. $ErrorActionPreference does
# not catch a native binary's exit code, which is the exact reason the previous
# sequence half-executed (L-139, L-141).

$ErrorActionPreference = 'Stop'
Set-Location C:\Users\Lenovo\qesis-mcp

function Guard($what) {
    if ($LASTEXITCODE -ne 0) {
        Write-Host "`nSTOPPED at: $what  (exit $LASTEXITCODE)" -ForegroundColor Red
        Write-Host "Nothing further ran. Paste the output above." -ForegroundColor Red
        exit 1
    }
}

Write-Host "`n=== 1. What is dirty, before anything is touched ===" -ForegroundColor Cyan
git status --short; Guard "git status"

# ops/SELFHEAL_LATEST.json is regenerated by every selfheal run. Discarding it
# is safe and it is the file blocking the switch. Nothing else is discarded.
Write-Host "`n=== 2. Discard the regenerated selfheal artefact only ===" -ForegroundColor Cyan
git checkout -- ops/SELFHEAL_LATEST.json; Guard "discard SELFHEAL_LATEST.json"

Write-Host "`n=== 3. Cut a branch FROM main this time, and prove it ===" -ForegroundColor Cyan
git fetch origin;                        Guard "git fetch"
git switch -c fix/report-l140-v2 origin/main; Guard "git switch -c from origin/main"

$base = (git merge-base origin/main HEAD).Trim(); Guard "merge-base"
$main = (git rev-parse origin/main).Trim();       Guard "rev-parse origin/main"
if ($base -ne $main) {
    Write-Host "ABORT: branch base $base is not origin/main $main." -ForegroundColor Red
    exit 1
}
Write-Host "OK  base == origin/main == $main" -ForegroundColor Green

Write-Host "`n=== 4. Take ONLY the two files from 752626f ===" -ForegroundColor Cyan
git checkout 752626f -- ops/DAILY_REPORT_2026-08-19.md ops/LESSONS_LEDGER.md
Guard "checkout the two files"

# L-141 is the lesson from THIS failure, so it cannot be inside 752626f. It is
# appended from a plain ASCII file rather than a here-string, because a
# here-string in Windows PowerShell 5 re-encodes and would corrupt the ledger.
Write-Host "`n=== 4b. Append L-141, the lesson from this very failure ===" -ForegroundColor Cyan
if (-not (Test-Path ops\L141_ENTRY.md)) {
    Write-Host "ABORT: ops\L141_ENTRY.md missing." -ForegroundColor Red; exit 1
}
Add-Content -Path ops\LESSONS_LEDGER.md -Value (Get-Content ops\L141_ENTRY.md -Raw)
Remove-Item ops\L141_ENTRY.md -Force
git add ops/LESSONS_LEDGER.md; Guard "stage the ledger"

# Single-instance ids are a build failure if duplicated (L-073). Assert it here
# rather than discovering it in CI.
$dupes = (Select-String -Path ops\LESSONS_LEDGER.md -Pattern '\*\*L-141' -AllMatches).Count
if ($dupes -ne 1) {
    Write-Host "ABORT: L-141 appears $dupes times. Ids are single-instance (L-073)." -ForegroundColor Red
    exit 1
}
Write-Host "OK  L-141 appears exactly once" -ForegroundColor Green

# The report's lesson count was written before L-141 existed.
Write-Host "`n=== 4c. Correct the lesson count in the report ===" -ForegroundColor Cyan
$rp = 'ops\DAILY_REPORT_2026-08-19.md'
$rt = (Get-Content $rp -Raw).Replace(
    '**L-131 to L-140.** Ten, and nine of them are mine.',
    '**L-131 to L-141.** Eleven, and ten of them are mine.')
Set-Content -Path $rp -Value $rt -NoNewline
git add $rp; Guard "stage the report"
Write-Host "OK  count updated" -ForegroundColor Green

Write-Host "`n=== 5. The diff about to be proposed ===" -ForegroundColor Cyan
git diff --cached --stat; Guard "diff --cached --stat"

Write-Host "`n=== 6. W-1, no em dash in the prose being committed (L-015) ===" -ForegroundColor Cyan
# There is no doctrine script under scripts\, verified by listing it, so the
# rule is asserted inline rather than named and left unenforced (L-054).
foreach ($f in @('ops\LESSONS_LEDGER.md', 'ops\DAILY_REPORT_2026-08-19.md')) {
    if ((Get-Content $f -Raw) -match [char]0x2014) {
        Write-Host "ABORT: em dash present in $f (W-1, L-015)." -ForegroundColor Red; exit 1
    }
}
Write-Host "OK  no em dash in either file" -ForegroundColor Green

Write-Host "`n=== 6b. The index still verifies on this tree ===" -ForegroundColor Cyan
python scripts\verify_index.py > $null 2>&1
if ($LASTEXITCODE -ne 0) { Write-Host "ABORT: verify_index failed." -ForegroundColor Red; exit 1 }
Write-Host "OK  verify_index passes" -ForegroundColor Green

Write-Host "`n=== 7. Commit, push, PR ===" -ForegroundColor Cyan
git commit -m "docs(report): remove fabricated PROD-1, register L-140 and L-141"
Guard "git commit"
git push -u origin fix/report-l140-v2; Guard "git push"

gh pr create --fill; Guard "gh pr create"
gh pr merge --rebase --auto
if ($LASTEXITCODE -ne 0) {
    Write-Host "`nPR opened but auto-merge was refused. Merge it in the UI." -ForegroundColor Yellow
}

Write-Host "`n=== 8. Close the unmergeable PR with its reason ===" -ForegroundColor Cyan
gh pr close 68 --comment @"
Superseded by fix/report-l140-v2, which is cut from main.

CAUSE. This branch was cut from 8b12760, not from main. The command sequence
that created it chained git calls in PowerShell, where a failed `git checkout
main` does not stop the following line, so `git checkout -b` branched from the
feature branch that was already checked out. main had meanwhile taken those
same three commits through a rebase, under different hashes, so git saw the
same content arriving twice with no common ancestor and could not reconcile it.

    git merge-base origin/main fix/report-l140  ->  8b12760
    git rev-parse origin/main                   ->  c5f0fc6

Proof the content is already on main:

    git cat-file -e origin/main:scripts/_walk.py                        present
    git cat-file -e origin/main:scripts/verify_no_plaintext_secrets.py  present

The genuine delta was two inserted lines in ops/LESSONS_LEDGER.md plus one new
file. Registered as L-141: a multi-step git sequence handed to an operator
checks the exit code of every step, because PowerShell continues past a failed
native command and a half-executed sequence produces a state nobody designed.
"@

Write-Host "`nDONE." -ForegroundColor Green
